# Generated by Django 4.2.4 on 2023-08-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='newdata',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PipeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(max_length=10)),
                ('length', models.CharField(max_length=10)),
                ('fluid_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.newdata')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
            ],
        ),
    ]
