# Generated by Django 4.2.4 on 2023-08-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipedata',
            name='fluid_data',
        ),
        migrations.RemoveField(
            model_name='pipedata',
            name='unit',
        ),
        migrations.DeleteModel(
            name='NewData',
        ),
        migrations.DeleteModel(
            name='PipeData',
        ),
    ]
