# Generated by Django 4.2.4 on 2023-08-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newdata_pipedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='density',
            field=models.FloatField(null=True),
        ),
    ]
